### ISSUE TITLE
crash on idea 2022.2

### ISSUE THREAD

**Issue by 0x1301FDF** [jonathanlermitage/intellij-extra-icons-plugin#106]
crash on every idea 2022.2(old UI,not new) startup. Plugin version 2022.1.7

java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:220)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:229)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.doFindChildById(VirtualDirectoryImpl.java:558)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findChild(FSRecords.java:539)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$1ParentFinder.findDescendantByIdPath(FSRecords.java:531)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findFileById(FSRecords.java:551)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:1436)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:58)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.processFilesContainingAnyKey(FileBasedIndexScanUtil.java:244)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1162)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:219)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:56)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:72)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:66)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.init(AbstractInFolderEnabler.java:34)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.verify(AbstractInFolderEnabler.java:75)
	at lermitage.intellij.extra.icons.ModelCondition.check(ModelCondition.java:115)
	at lermitage.intellij.extra.icons.Model.check(Model.java:300)
	at lermitage.intellij.extra.icons.BaseIconProvider.getIcon(BaseIconProvider.java:222)
	at lermitage.intellij.extra.icons.BaseIconProvider.getIcon(BaseIconProvider.java:169)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:215)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:149)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$5(EditorsSplitters.java:419)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:206)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jonathanlermitage** [comment]
@0x1301FDF  Can you go to `Help` > `Collect Logs and Diagnostic Data`, and post files.  
Same thing for `Help` > `About` > `Copy`.  
I can't reproduce for now, but the log files and the IDE infos (list of installed plugins, etc) would help me to reproduce this issue. Thx!

**Comment by jonathanlermitage** [comment]
It seems to be a problem with the file index generated by the IDE. Could you please try to clear the file system cache and Local History? (`File` > `Invalidate Caches...`).

**Comment by jonathanlermitage** [comment]
Can you also try this build? 
[Extra Icons-2022.1.7.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/9260900/Extra.Icons-2022.1.7.zip)
Exception now displays a notification only, and the plugin should not crash anymore.

**Comment by jonathanlermitage** [comment]
Can you also try this build?
[Extra Icons-2022.1.7.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/9260971/Extra.Icons-2022.1.7.zip)

Exception now displays a notification only, and the plugin should not crash anymore.

**Comment by jonathanlermitage** [comment]
Nota: I think there is already an issue in IJ bugtracker: https://youtrack.jetbrains.com/issue/IDEA-291382/Assertion-failed-at-VirtualDirectoryImpldoFindChildById

**Comment by 0x1301FDF** [comment]
> @0x1301FDF It seems to be a problem with the file index generated by the IDE (`FilenameIndex.getVirtualFilesByName` IDE method). Could you please try to clear the file system cache and Local History? (`File` > `Invalidate Caches...`).

yeah, after i clear the cache, it seems no longer crash again, thanks!

**Comment by jonathanlermitage** [comment]
Found a workaround 🎉thx Andreas Perhab comment https://youtrack.jetbrains.com/issue/IDEA-291382/Assertion-failed-at-VirtualDirectoryImpldoFindChildById#focus=Comments-27-6445738.0-0
