### ISSUE TITLE
java.lang.Exception: Helm folder icon Enabler can't query IDE filename index: project ij-extra-tci is not initialized. Some icons override won't work.

### ISSUE THREAD

**Issue by jonathanlermitage** [jonathanlermitage/intellij-extra-icons-plugin#128]
## Running environment
- Extra Icons plugin version - 2023.2.2
- IDE - IntelliJ IDEA 2023.1.2 Preview
- OS - Windows 10.0

## Bug description
Loading project. Fist indexing was not done yet.

## IDE - additional info
N/A

## IDE - stack trace
```
Canceled init of Helm folder icon Enabler

java.lang.Exception: Helm folder icon Enabler can't query IDE filename index: project ij-extra-tci is not initialized. Some icons override won't work.
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.initWithIdeFileIndex(AbstractInFolderEnabler.java:67)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.lambda$init$0(AbstractInFolderEnabler.java:51)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.lambda$init$1(AbstractInFolderEnabler.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jonathanlermitage** [comment]
Fixed in commit 6957d1a0
