### ISSUE TITLE
kotlin.UninitializedPropertyAccessException: lateinit property mainSplitters has not been initialized

### ISSUE THREAD

**Issue by gumdamxxx** [jonathanlermitage/intellij-extra-icons-plugin#134]
## Running environment
- Extra Icons plugin version - 2023.2.3
- IDE - IntelliJ IDEA 2023.1.2
- OS - Windows 10.0

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Collect Logs and Diagnostic Data</kbd>.

## IDE - additional info
N/A

## IDE - stack trace
```
Failed to refresh editor tabs icon

kotlin.UninitializedPropertyAccessException: lateinit property mainSplitters has not been initialized
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getMainSplitters(FileEditorManagerImpl.kt:132)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getAllSplitters(FileEditorManagerImpl.kt:480)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getWindows(FileEditorManagerImpl.kt:619)
	at lermitage.intellij.extra.icons.utils.ProjectUtils.refreshProject(ProjectUtils.java:35)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.lambda$init$0(AbstractInFolderEnabler.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.lambda$init$1(AbstractInFolderEnabler.java:57)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jonathanlermitage** [comment]
@gumdamxxx  Can you please try this release 
[Extra Icons-2023.2.3.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11503634/Extra.Icons-2023.2.3.zip)
? It may be fixed now. Thx!
