### ISSUE TITLE
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by maicol07** [jonathanlermitage/intellij-extra-icons-plugin#140]
## Running environment
- Extra Icons plugin version - 2023.2.5-231
- IDE - PhpStorm 2023.2 EAP
- OS - Linux 5.15.90.1-microsoft-standard-wsl2

## Bug description
[phpstorm-logs-20230605-1843567203053002418722287.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11654819/phpstorm-logs-20230605-1843567203053002418722287.zip)

## IDE - additional info
N/A

## IDE - stack trace
```
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:367)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:129)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:129)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:75)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isUnderIgnored(ProjectFileIndexImpl.java:64)
	at com.intellij.openapi.roots.impl.ProjectFileIndexFacade.isUnderIgnored(ProjectFileIndexFacade.java:66)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.isExcludedOrIgnored(FileManagerImpl.java:427)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectoryImpl(FileManagerImpl.java:413)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:405)
	at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:171)
	at com.intellij.psi.AbstractFileViewProvider.shouldCreatePsi(AbstractFileViewProvider.java:89)
	at com.intellij.psi.SingleRootFileViewProvider.createFile(SingleRootFileViewProvider.java:149)
	at com.intellij.psi.SingleRootFileViewProvider.getPsiInner(SingleRootFileViewProvider.java:105)
	at com.intellij.psi.AbstractFileViewProvider.getPsi(AbstractFileViewProvider.java:194)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.areViewProvidersEquivalent(FileManagerImpl.java:544)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.shouldResurrect(FileManagerImpl.java:641)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.evaluateValidity(FileManagerImpl.java:609)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findCachedViewProvider(FileManagerImpl.java:226)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findViewProvider(FileManagerImpl.java:183)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.findFile(FileManagerImpl.java:364)
	at com.intellij.psi.impl.PsiManagerImpl.findFile(PsiManagerImpl.java:158)
	at lermitage.intellij.extra.icons.BaseIconProvider.getIcon(BaseIconProvider.java:148)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNodeRenderer.lambda$setIcon$0(ChangesBrowserNodeRenderer.java:108)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.ExtensionPointName.computeSafeIfAny(ExtensionPointName.kt:57)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNodeRenderer.setIcon(ChangesBrowserNodeRenderer.java:108)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserChangeNode.setIcon(ChangesBrowserChangeNode.java:96)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserChangeNode.lambda$render$0(ChangesBrowserChangeNode.java:82)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:935)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:63)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserChangeNode.render(ChangesBrowserChangeNode.java:54)
	at com.intellij.openapi.vcs.changes.ui.ChangesBrowserNodeRenderer.customizeCellRenderer(ChangesBrowserNodeRenderer.java:59)
	at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:125)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:57)
	at com.intellij.openapi.vcs.changes.ui.ChangesTreeCellRenderer.getTreeCellRendererComponent(ChangesTreeCellRenderer.kt:50)
	at com.intellij.openapi.vcs.changes.ui.HoverChangesTree$HoverChangesTreeRenderer.getTreeCellRendererComponent(HoverChangesTree.kt:86)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:187)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:564)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:555)
	at java.desktop/javax.swing.tree.FixedHeightLayoutCache.getBounds(FixedHeightLayoutCache.java:201)
	at com.intellij.ui.tree.ui.DefaultTreeUI.paint(DefaultTreeUI.java:249)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:845)
	at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:334)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1115)
	at com.intellij.ui.treeStructure.Tree.paint(Tree.java:251)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:736)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:237)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:955)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1124)

**Comment by jonathanlermitage** [comment]
Can you please try this version: [Extra Icons-2023.2.5-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11702381/Extra.Icons-2023.2.5-231.zip)
 It should be better.

**Comment by jonathanlermitage** [comment]
Plugin release 2023.2.6 published to the marketplace. It should be available in ~2 days.

**Comment by maicol07** [comment]
> Can you please try this version: [Extra Icons-2023.2.5-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/11702381/Extra.Icons-2023.2.5-231.zip)
>  It should be better.

Installed some days ago and didn't noticed anything, so it is fixed indeed
