### ISSUE TITLE
com.intellij.diagnostic.PluginException: null [Plugin: lermitage.intellij.extra.icons]

### ISSUE THREAD

**Issue by nicekiwi** [jonathanlermitage/intellij-extra-icons-plugin#142]
## Running environment
- Extra Icons plugin version - 2023.2.6-231
- IDE - PhpStorm 2023.1.2
- OS - macOS 13.4

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Collect Logs and Diagnostic Data</kbd>.

## IDE - additional info
I opened PHPStorm

## IDE - stack trace
```
com.intellij.diagnostic.PluginException: null [Plugin: lermitage.intellij.extra.icons]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)...
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:158)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:148)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
	at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceled(ProgressWrapper.java:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:141)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.serviceContainer.ContainerUtilKt.checkCanceledIfNotInClassInit(containerUtil.kt:17)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:988)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.openapi.options.ConfigurableEP.instantiateConfigurableProvider(ConfigurableEP.java:319)
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:297)
	... 32 more

**Comment by jonathanlermitage** [comment]
Hi,  
can you please attach the IDE log files?  
Thanks!

**Comment by jonathanlermitage** [comment]
Upvoting https://youtrack.jetbrains.com/issue/IDEA-307476/com.intellij.diagnostic.PluginException-null-Plugin-com.perl5 would help.

**Comment by jonathanlermitage** [comment]
Will publish 2023.3 plugin release soon, which reworked a lot of code. Will re-open if needed.
