### ISSUE TITLE
com.intellij.diagnostic.PluginException: null [Plugin: lermitage.intellij.extra.icons]

### ISSUE THREAD

**Issue by nicekiwi** [jonathanlermitage/intellij-extra-icons-plugin#149]
## Running environment
- Extra Icons plugin version - 2023.2.8-231
- IDE - PhpStorm 2023.1.4
- OS - macOS 13.5

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Collect Logs and Diagnostic Data</kbd>.
[phpstorm-logs-20230728-1347292598536320218596699.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12189342/phpstorm-logs-20230728-1347292598536320218596699.zip)

I restarted the IDE to install plugin updates.

## IDE - additional info
N/A

## IDE - stack trace
```
com.intellij.diagnostic.PluginException: null [Plugin: lermitage.intellij.extra.icons]
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:311)...
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:158)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:148)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:103)
	at com.intellij.openapi.progress.util.ProgressWrapper.checkCanceled(ProgressWrapper.java:82)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:141)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:227)
	at com.intellij.serviceContainer.ContainerUtilKt.checkCanceledIfNotInClassInit(containerUtil.kt:17)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:988)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1051)
	at com.intellij.openapi.options.ConfigurableEP.instantiateConfigurableProvider(ConfigurableEP.java:319)
	at com.intellij.openapi.options.ConfigurableEP.createProducer(ConfigurableEP.java:297)
	... 32 more

**Comment by jonathanlermitage** [comment]
Thank you very much @nicekiwi for the log files, this is very helpful 👍.  
Did the error report appear when you invoked a Search Everywhere action? (Ctrl Shift F, or something like that)

**Comment by jonathanlermitage** [comment]
One last thing: do you have a sample project?  
I am trying to reproduce this issue.

**Comment by nicekiwi** [comment]
@jonathanlermitage I'm not sure, I believe after the restart the error reporting notification was just there, there were two of them for what looked like the same error.

Your plugin was not one of the updates the IDE was restarted to activate.

**Comment by nicekiwi** [comment]
The main project is a laravel 9 app with a heap of typescript and angularjs, I don't have a sample app persay.

**Comment by jonathanlermitage** [comment]
If my understanding is correct, you see the error notification only after the plugin update?  
Does it happen after the second IDE restart? (not after plugins upgrade) 

I noticed something weird, since IJ ~2022: when I upgrade some plugins, and if I click the "Restart IDE" button, the next start is a bit buggy. Caching problems, Gradle projects can't load, and some weird errors.  
As a workaround, when I upgrade plugins, I don't hit the Restart button. I close the IDE manually, then I start it normally. This is much better. I was wondering if it was a problem with my IDE, but if you faced the same problem, I will raise an issue on YouTrack.

**Comment by jonathanlermitage** [comment]
Will re-open if I get more info. Can do nothing for now.
