### ISSUE TITLE
java.lang.Throwable: TreeUI should be accessed only from EDT

### ISSUE THREAD

**Issue by rudra-superflux** [jonathanlermitage/intellij-extra-icons-plugin#157]
## Running environment
- Extra Icons plugin version - 2023.2.11-231
- IDE - JetBrains Rider 2023.3 EAP 1
- OS - Windows 11.0

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Show Log in Explorer</kbd>, then pick `idea.log`.

## IDE - additional info
N/A

## IDE - stack trace
```
java.lang.Throwable: TreeUI should be accessed only from EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.tree.ui.DefaultTreeUI.isValid(DefaultTreeUI.java:217)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRowCount(DefaultTreeUI.java:748)
	at java.desktop/javax.swing.JTree.getRowCount(JTree.java:1697)
	at com.intellij.util.ui.tree.TreeUtil.collectExpandedObjects(TreeUtil.java:192)
	at com.intellij.util.ui.tree.TreeUtil.collectExpandedPaths(TreeUtil.java:175)
	at com.intellij.ide.util.treeView.TreeState.createOn(TreeState.java:173)
	at com.jetbrains.rider.projectView.views.SolutionViewPaneBase.createTreeState(SolutionViewPaneBase.kt:286)
	at com.intellij.ide.projectView.impl.AbstractProjectViewPane.saveExpandedPaths(AbstractProjectViewPane.java:702)
	at com.jetbrains.rider.projectView.views.SolutionViewPaneBase.updateFromRoot(SolutionViewPaneBase.kt:292)
	at com.jetbrains.rider.projectView.views.SolutionViewPaneBase.updateFromRoot(SolutionViewPaneBase.kt:289)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.refresh(ProjectViewImpl.java:1156)
	at lermitage.intellij.extra.icons.utils.ProjectUtils.refreshProject(ProjectUtils.java:29)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.init(AbstractInFolderEnabler.java:52)
	at lermitage.intellij.extra.icons.enablers.EnablerUtils.lambda$forceInitAllEnablers$0(EnablerUtils.java:24)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at lermitage.intellij.extra.icons.enablers.EnablerUtils.forceInitAllEnablers(EnablerUtils.java:24)
	at lermitage.intellij.extra.icons.activity.EnablerServicesPostStartupActivity.lambda$execute$0(EnablerServicesPostStartupActivity.java:24)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:75)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:122)
	at lermitage.intellij.extra.icons.activity.EnablerServicesPostStartupActivity.execute(EnablerServicesPostStartupActivity.java:23)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:466)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by jonathanlermitage** [comment]
@rudra-superflux as a workaround, can you go to plugin's settings and disable Filename index usage? It should work better.  
![image](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/assets/857535/d94b62da-d5e4-4e25-be26-c19cbd3af2f1)

**Comment by jonathanlermitage** [comment]
@rudra-superflux can you please try this build [Extra Icons-2023.2.11-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12874465/Extra.Icons-2023.2.11-231.zip)?

**Comment by jonathanlermitage** [comment]
@rudra-superflux here is a new release. Can you please try it? It should be much better.  
-> [Extra Icons-2023.2.11-231.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/12875958/Extra.Icons-2023.2.11-231.zip)
