### ISSUE TITLE
java.lang.Throwable: TreeUI should be accessed only from EDT

### ISSUE THREAD

**Issue by RajithaAtGit** [jonathanlermitage/intellij-extra-icons-plugin#163]
## Running environment
- Extra Icons plugin version - 2023.2.11-231
- IDE - IntelliJ IDEA 2023.3 EAP
- OS - Windows 10.0

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Show Log in Explorer</kbd>, then pick `idea.log`.

## IDE - additional info
N/A

## IDE - stack trace
```
java.lang.Throwable: TreeUI should be accessed only from EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.tree.ui.DefaultTreeUI.isValid(DefaultTreeUI.java:216)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRowCount(DefaultTreeUI.java:772)
	at java.desktop/javax.swing.JTree.getRowCount(JTree.java:1697)
	at com.intellij.util.ui.tree.TreeUtil.collectExpandedObjects(TreeUtil.java:192)
	at com.intellij.util.ui.tree.TreeUtil.collectExpandedPaths(TreeUtil.java:175)
	at com.intellij.ide.util.treeView.TreeState.createOn(TreeState.java:173)
	at com.intellij.ide.util.treeView.TreeState.createOn(TreeState.java:169)
	at com.intellij.ide.projectView.impl.AbstractProjectViewPane.createTreeState(AbstractProjectViewPane.java:696)
	at com.intellij.ide.projectView.impl.AbstractProjectViewPane.saveExpandedPaths(AbstractProjectViewPane.java:702)
	at com.intellij.ide.scopeView.ScopeViewPane.updateFromRoot(ScopeViewPane.java:225)
	at com.intellij.ide.projectView.impl.ProjectViewImpl.refresh(ProjectViewImpl.java:1154)
	at lermitage.intellij.extra.icons.utils.ProjectUtils.refreshProject(ProjectUtils.java:29)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.init(AbstractInFolderEnabler.java:52)
	at lermitage.intellij.extra.icons.enablers.EnablerUtils.lambda$forceInitAllEnablers$0(EnablerUtils.java:24)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at lermitage.intellij.extra.icons.enablers.EnablerUtils.forceInitAllEnablers(EnablerUtils.java:24)
	at lermitage.intellij.extra.icons.activity.EnablerServicesPostStartupActivity.lambda$execute$0(EnablerServicesPostStartupActivity.java:24)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode$lambda$2(DumbService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:928)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:122)
	at lermitage.intellij.extra.icons.activity.EnablerServicesPostStartupActivity.execute(EnablerServicesPostStartupActivity.java:23)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$launchActivity$1.invokeSuspend(StartupManagerImpl.kt:467)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by jonathanlermitage** [comment]
Hi @RajithaAtGit  
Can you please upgrade to Extra icons 2023.2.12-231 and say if this error is gone? Thanks!

**Comment by jonathanlermitage** [comment]
Please reopen if needed 😎
