### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.ui.docking.DockManager because container is already disposed (container=Project(name=pythonProject, containerState=DISPOSE_COMPLETED, componentStore=/Users/adrian/Source/Repos/pythonProject) (disposed))

### ISSUE THREAD

**Issue by AdyGCode** [jonathanlermitage/intellij-extra-icons-plugin#165]
## Running environment
- Extra Icons plugin version - 2023.2.12-231
- IDE - PyCharm 2023.2.3
- OS - macOS 14.0

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Show Log in Explorer</kbd>, then pick `idea.log`.

## IDE - additional info
N/A

## IDE - stack trace
```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.ui.docking.DockManager because container is already disposed (container=Project(name=pythonProject, containerState=DISPOSE_COMPLETED, componentStore=/Users/adrian/Source/Repos/pythonProject) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:698)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.intellij.ui.docking.DockManager.getInstance(DockManager.java:22)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getAllSplitters(FileEditorManagerImpl.kt:472)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.refreshIcons(FileEditorManagerImpl.kt:2010)
	at lermitage.intellij.extra.icons.utils.ProjectUtils.lambda$refreshProject$1(ProjectUtils.java:38)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:208)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:190)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:478)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:121)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithoutImplicitRead(ApplicationImpl.java:1485)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by jonathanlermitage** [comment]
Hi @AdyGCode  
What were you doing when this error report appeared? It would help me a lot. Thanks!

**Comment by AdyGCode** [comment]
Hi Jonathan

To be honest, not sure, as i was in the midst of updating / downgrading PyCharm & some plugins at the time.

Keep it on back burner/close and if it happens again I'll be a bit more forthcoming on what caused it.

I'm not ususlly vague with my error reports, so apologies again.

Ady

Adrian Gould
Educator, Coder, Hockey Goalie, Geek & Nerd

**Comment by jonathanlermitage** [comment]
Thanks for the details! Some users experienced similar problems on IDE/plugins upgrade. Unfortunately, these bugs are very hard to debug. I have planned a huge refactoring/rework of my plugin for next year. I cross fingers 😁

**Comment by jonathanlermitage** [comment]
This issue may be fixed in this build: 
[Extra Icons-2023.2.12-231-no-license.zip](https://github.com/jonathanlermitage/intellij-extra-icons-plugin/files/13079661/Extra.Icons-2023.2.12-231-no-license.zip)
I will try to publish a new release on the marketplace asap.
