### ISSUE TITLE
java.lang.Throwable: ensureFileBelongsToIndexableFilter returned ADDED or PRESENT, but findProjectForFileId returned null for file: file:///Users/norris.shelton/IdeaProjects/newcam/newcam-server/src/main/java/com/twinspires/cam/response/SearchCustomerResponse.java

### ISSUE THREAD

**Issue by norris-shelton** [jonathanlermitage/intellij-extra-icons-plugin#180]
## Running environment
- Plugin version: 2024.3.1
- IDE: IntelliJ IDEA 2023.3.4
- OS: macOS 14.3.1

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Show Log in Explorer</kbd>, then pick `idea.log`.

## IDE - additional info
N/A

## IDE - stack trace
```
java.lang.Throwable: ensureFileBelongsToIndexableFilter returned ADDED or PRESENT, but findProjectForFileId returned null for file: file:///Users/norris.shelton/IdeaProjects/newcam/newcam-server/src/main/java/com/twinspires/cam/response/SearchCustomerResponse.java
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.indexing.FileBasedIndexImpl.scheduleFileForIndexing(FileBasedIndexImpl.java:1805)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.process(ChangedFilesCollector.java:242)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$process$0(ChangedFilesCollector.java:284)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$2(CoreProgressManager.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$3(CoreProgressManager.java:236)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:57)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:236)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:227)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$process$1(ChangedFilesCollector.java:283)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:246)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.process(ChangedFilesCollector.java:281)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:115)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:278)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:230)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.ensureUpToDate(FileBasedIndexScanUtil.java:52)
	at com.intellij.util.indexing.FileBasedIndexScanUtil.processFilesContainingAnyKey(FileBasedIndexScanUtil.java:238)
	at com.intellij.util.indexing.FileBasedIndexImpl.processFilesContainingAnyKey(FileBasedIndexImpl.java:1121)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByNames(FilenameIndex.java:214)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:62)
	at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:78)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.initWithIDEFileIndex(AbstractInFolderEnabler.java:126)
	at lermitage.intellij.extra.icons.enablers.AbstractInFolderEnabler.init(AbstractInFolderEnabler.java:47)
	at lermitage.intellij.extra.icons.activity.RefreshIconsListenerPrjActivity.lambda$reinitIconEnablers$0(RefreshIconsListenerPrjActivity.java:70)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at lermitage.intellij.extra.icons.activity.RefreshIconsListenerPrjActivity.lambda$reinitIconEnablers$1(RefreshIconsListenerPrjActivity.java:70)
	at com.intellij.openapi.project.DumbService.runReadActionInSmartMode(DumbService.kt:117)
	at lermitage.intellij.extra.icons.activity.RefreshIconsListenerPrjActivity.lambda$reinitIconEnablers$2(RefreshIconsListenerPrjActivity.java:66)
	at lermitage.intellij.extra.icons.utils.IJUtils.lambda$runInBGT$1(IJUtils.java:83)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at lermitage.intellij.extra.icons.utils.IJUtils.lambda$runInBGT$3(IJUtils.java:81)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by jonathanlermitage** [comment]
Opened https://youtrack.jetbrains.com/issue/IJSDK-1979/FilenameIndex.getVirtualFilesByName-fails-saying-ensureFileBelongsToIndexableFilter-returned-ADDED-or-PRESENT-but  
I query the filename index for a specific set of files (Helm files, Angular config files, etc, in order to detect Helm, Angular support...), but the error is about another file "SearchCustomerResponse.java". This is probably a bug in the IDE. Wait & see.

**Comment by jonathanlermitage** [comment]
@norris-shelton it should be fixed in latest IntelliJ EAP and in the upcoming IntelliJ 2024.1  
-> https://youtrack.jetbrains.com/issue/IDEA-348939/FilenameIndex.getVirtualFilesByName-fails-saying-ensureFileBelongsToIndexableFilter-returned-ADDED-or-PRESENT-but#focus=Comments-27-9449610.0-0
