### ISSUE TITLE
java.lang.Throwable: Standard architecture not found for iOS among:

### ISSUE THREAD

**Issue by danny-su** [jonathanlermitage/intellij-extra-icons-plugin#181]
## Running environment
- Plugin version: 2024.3.2
- IDE: AppCode 2023.1.4
- OS: macOS 14.4

## Bug description
Please include steps to reproduce (like `go to...`/`click on...` etc.) + expected and actual behaviour.  
Please attach **IDE logs**. Open your IDE and go to <kbd>Help</kbd>, <kbd>Show Log in Explorer</kbd>, then pick `idea.log`.

## IDE - additional info
N/A

## IDE - stack trace
```
java.lang.Throwable: Standard architecture not found for iOS among:

	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.jetbrains.cidr.xcode.frameworks.ApplePlatform.getStandardNativeArchitecture(ApplePlatform.java:355)
	at com.jetbrains.cidr.xcode.frameworks.AppleSdkManager.getStandardNativeArchitectureId(AppleSdkManager.java:485)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSettingsResolver$8.getDeclaredBuildSettingValues(BuildSettingsResolver.java:636)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSettingsResolver.convertValuesToSpecs(BuildSettingsResolver.java:453)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSettingsResolver.getSpecsTables(BuildSettingsResolver.java:438)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.CachingBuildSettingsResolver.lambda$createCachedSpecs$6(CachingBuildSettingsResolver.java:67)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.CachingBuildSettingsResolver.lambda$cached$5(CachingBuildSettingsResolver.java:61)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.CachingBuildSettingsResolver.getSpecsTables(CachingBuildSettingsResolver.java:135)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSettingsResolver.doGetUnresolvedValueWithSource(BuildSettingsResolver.java:314)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.CachingBuildSettingsResolver.doGetUnresolvedValueWithSource(CachingBuildSettingsResolver.java:121)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSettingsResolver.doGetUnresolvedValueWithSource(BuildSettingsResolver.java:301)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSettingsResolver.getUnresolvedValueWithSource(BuildSettingsResolver.java:258)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSetting.getUnresolvedValue(BuildSetting.java:257)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSetting.getUnresolvedValue(BuildSetting.java:245)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSetting.getUnresolvedString(BuildSetting.java:273)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSetting.getString(BuildSetting.java:114)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSetting.getAbsoluteFile(BuildSetting.java:143)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSetting.getAbsolutePath(BuildSetting.java:132)
	at com.jetbrains.cidr.xcode.frameworks.buildSystem.BuildSetting.getAbsolutePath(BuildSetting.java:126)
	at com.jetbrains.cidr.xcode.model.PBXReference.resolveSourceTree(PBXReference.java:310)
	at com.jetbrains.cidr.xcode.model.PBXReference.resolvePath(PBXReference.java:271)
	at com.jetbrains.cidr.xcode.model.PBXReference.lambda$doFindFile$2(PBXReference.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.jetbrains.cidr.xcode.model.PBXReference.doFindFile(PBXReference.java:381)
	at com.jetbrains.cidr.xcode.model.PBXReference.findFile(PBXReference.java:359)
	at com.jetbrains.cidr.xcode.model.PBXReference.findFile(PBXReference.java:315)
	at com.jetbrains.cidr.projectView.XcodeProjectItemPresenter.getVirtualFile(XcodeProjectItemPresenter.java:26)
	at com.jetbrains.cidr.projectView.XcodeViewNode.getVirtualFile(XcodeViewNode.java:295)
	at lermitage.intellij.extra.icons.BaseIconProvider.decorate(BaseIconProvider.java:256)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.lambda$decorate$0(CompoundProjectViewNodeDecorator.java:45)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.forEach(CompoundProjectViewNodeDecorator.java:51)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.decorate(CompoundProjectViewNodeDecorator.java:45)
	at com.jetbrains.cidr.projectView.XcodeViewNode.update(XcodeViewNode.java:289)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:90)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:33)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:485)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:345)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:568)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:464)
	at com.intellij.ui.tree.AsyncTreeModel$Command.get(AsyncTreeModel.java:430)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:304)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1100)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)

**Comment by jonathanlermitage** [comment]
Did you face this issue again? When did it happen (did you open the settings panel, did you simply open a project, things like that)? More context information would help. Thanks!

**Comment by danny-su** [comment]
@jonathanlermitage It seems like the issue disappeared.
