### ISSUE TITLE
NoSuchFileException: Problem after dynamic update?

### ISSUE THREAD

**Issue by ahus1** [jonathanlermitage/intellij-extra-icons-plugin#47]
One of the users of the AsciiDoc plugin I maintain reported the following exception: a missing JAR file for the Extra Icons plugin. 

Can this be due to a dynamically updated plugin Extra Icons plugin? Maybe the plugin update was incomplete/waiting for a restart, or some bundles were still pointing to the old file?

Unfortunately the user didn't provide additional information and stayed anonymous. 

```
java.nio.file.NoSuchFileException: ***/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/203.7148.57.plugins/Extra Icons/lib/ij-extra-icons-1.46.1.201.jar
    at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
    at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
    at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
    at java.nio.file.Files.readAttributes(Files.java:1838)
    at java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
    at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
    at java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
    at java.util.zip.ZipFile.<init>(ZipFile.java:247)
    at java.util.zip.ZipFile.<init>(ZipFile.java:177)
    at java.util.zip.ZipFile.<init>(ZipFile.java:148)
    at com.intellij.util.lang.JarLoader.createZipFile(JarLoader.java:322)
    at com.intellij.util.lang.JarLoader.getZipFile(JarLoader.java:312)
    at com.intellij.util.lang.JarLoader.getResource(JarLoader.java:217)
    at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.findInLoader(ClassPath.java:374)
    at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.process(ClassPath.java:369)
    at com.intellij.util.lang.ClassPath$ResourceStringLoaderIterator.process(ClassPath.java:366)
    at com.intellij.util.lang.ClasspathCache.iterateLoaders(ClasspathCache.java:150)
    at com.intellij.util.lang.ClassPath.getResource(ClassPath.java:102)
    at com.intellij.util.lang.UrlClassLoader.findResourceImpl(UrlClassLoader.java:419)
    at com.intellij.util.lang.UrlClassLoader.getResourceAsStream(UrlClassLoader.java:442)
    at com.intellij.ide.plugins.cl.PluginClassLoader.getOwnResourceAsStream(PluginClassLoader.java:379)
    at com.intellij.ide.plugins.cl.PluginClassLoader.getResourceAsStream(PluginClassLoader.java:372)
    at com.intellij.util.ImageLoader.getResourceData(ImageLoader.java:325)
    at com.intellij.util.SVGLoader.loadFromClassResource(SVGLoader.java:155)
    at com.intellij.util.ImageLoader.loadByDescriptor(ImageLoader.java:299)
    at com.intellij.util.ImageLoader.load(ImageLoader.java:224)
    at com.intellij.openapi.util.IconLoader$ImageDataResolverImpl.loadImage(IconLoader.java:1266)
    at com.intellij.openapi.util.IconLoader$CachedImageIcon.loadImage(IconLoader.java:1017)
    at com.intellij.openapi.util.IconLoader$ScaledIconCache.getOrScaleIcon(IconLoader.java:1087)
    at com.intellij.openapi.util.IconLoader$CachedImageIcon.getRealIcon(IconLoader.java:905)
    at com.intellij.openapi.util.IconLoader$CachedImageIcon.paintIcon(IconLoader.java:828)
    at com.intellij.ui.LayeredIcon.paintIcon(LayeredIcon.java:229)
    at com.intellij.ui.RowIcon.paintIcon(RowIcon.java:160)
    at com.intellij.ui.DeferredIconImpl.paintIcon(DeferredIconImpl.java:146)
    at com.intellij.ui.SimpleColoredComponent.paintIcon(SimpleColoredComponent.java:1052)
    at com.intellij.ui.SimpleColoredComponent.doPaintIcon(SimpleColoredComponent.java:765)
    at com.intellij.ui.SimpleColoredComponent.doPaint(SimpleColoredComponent.java:725)
    at com.intellij.ui.SimpleColoredComponent.paintComponent(SimpleColoredComponent.java:712)
    at javax.swing.JComponent.paint(JComponent.java:1077)
    at javax.swing.CellRendererPane.paintComponent(CellRendererPane.java:165)
    at com.intellij.ui.tree.ui.DefaultTreeUI.paint(DefaultTreeUI.java:246)
    at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
    at javax.swing.JComponent.paintComponent(JComponent.java:800)
    at com.intellij.ui.treeStructure.Tree.paintComponent(Tree.java:321)
    at javax.swing.JComponent.paint(JComponent.java:1077)
    at com.intellij.ui.treeStructure.Tree.paint(Tree.java:235)
    at javax.swing.JComponent.paintChildren(JComponent.java:910)
    at javax.swing.JComponent.paint(JComponent.java:1086)
    at javax.swing.JViewport.paint(JViewport.java:737)
    at com.intellij.ui.components.JBViewport.paint(JBViewport.java:241)
    at javax.swing.JComponent.paintToOffscreen(JComponent.java:5263)
    at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:246)
    at javax.swing.RepaintManager.paint(RepaintManager.java:1333)
    at javax.swing.JComponent._paintImmediately(JComponent.java:5211)
    at javax.swing.JComponent.paintImmediately(JComponent.java:5021)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:868)
    at javax.swing.RepaintManager$4.run(RepaintManager.java:851)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
    at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
    at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
    at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:762)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
    at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
    at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
    at java.awt.Dialog.show(Dialog.java:1063)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:694)
    at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
    at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1715)
    at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1674)
    at com.intellij.openapi.fileChooser.ex.FileSaverDialogImpl.save(FileSaverDialogImpl.java:81)
    at org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel.saveImage(AsciiDocJCEFHtmlPanel.java:550)
    at org.asciidoc.intellij.editor.jcef.AsciiDocJCEFHtmlPanel.lambda$reregisterHandlers$8(AsciiDocJCEFHtmlPanel.java:408)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:216)
    at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:24)
    at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:199)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:324)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:85)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:134)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
    at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:190)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
    at java.awt.EventQueue$4.run(EventQueue.java:727)
    at java.awt.EventQueue$4.run(EventQueue.java:721)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:976)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:843)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:454)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:773)
    at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:453)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:822)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:501)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by jonathanlermitage** [comment]
Yeah, unfortunately I would need more information.  
Dynamic update of Extra Icons has been disabled in 1.46 release: user has to restart the IDE to complete the update. Also, the plugin path seems good. Maybe an IntelliJ bug :-p

**Comment by jonathanlermitage** [comment]
@ahus1 Actually, it could be a problem with JetBrains Toolbox: it installs your IDE in a specific path, like `***/.local/share/JetBrains/Toolbox/apps/...`. Here, the user started IntelliJ 203 (2020.3), you can see `.../IDEA-U/ch-0/203.7148.57.plugins/` in the plugin path.  
When the Toolbox upgrade the IDE itself, per example from `203.7148.57` to `203.7717.45` (the latest version), the IDE shortcut in the macOS launch-bar (or MS Windows taskbar, etc) may stick to the old release. User has to unpin the shortcut from the launch-bar, start the latest IDE via Toolbox, then pin the new shortcut.  
I faced this issue many times on Windows, but I can't confirm it's still buggy on macOS or Linux.

**Comment by ahus1** [comment]
Alright; if you think there is nothing else to do here, please feel free to close this issue.
